### ISSUE TITLE
PWA

### ISSUE THREAD

**Issue by stancl** [LeanAdmin/feature-discussions#1]
Make the project very PWA-friendly by storing the static layout and only swapping the rendered page with Turbolinks.

This could make Lean admin panels installable on mobile devices! Of course offline mode won't work, but having an app for your admin panel can be very beneficial, especially if your customers are non-technical and use the admin panel on a daily basis.

**Comment by molcsab** [comment]
I absolutely need this. The new application I am developing with LeanAdmin has to be able to work in PWA mode

**Comment by stancl** [comment]
Turbolinks is now implemented and will be released in the coming days.

**Comment by stancl** [comment]
<img width="1733" alt="Screen Shot 2021-03-04 at 23 49 46" src="https://user-images.githubusercontent.com/33033094/110043451-b6536200-7d47-11eb-866c-6f8549e0040f.png">
