### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by stancl** [LeanAdmin/feature-discussions#11]
With the default theme being so clean, adding dark mode could be pretty straightforward.

Tailwind 2 makes this even easier.

**Comment by molcsab** [comment]
This would be a nice addition

**Comment by stancl** [comment]
@molcsab No need to comment on every issue, just use reactions please.

**Comment by stancl** [comment]
<img width="1597" alt="Screen Shot 2021-01-21 at 20 31 13" src="https://user-images.githubusercontent.com/33033094/105403596-3787e700-5c29-11eb-9d6f-c6a5aa8e1160.png">
<img width="1594" alt="Screen Shot 2021-01-21 at 20 37 14" src="https://user-images.githubusercontent.com/33033094/105403605-3a82d780-5c29-11eb-88ee-13f545345f9f.png">
<img width="449" alt="Screen Shot 2021-01-21 at 20 43 03" src="https://user-images.githubusercontent.com/33033094/105403661-4f5f6b00-5c29-11eb-96a5-ce8ac5cbc937.png">
<img width="1597" alt="Screen Shot 2021-01-21 at 20 43 42" src="https://user-images.githubusercontent.com/33033094/105403696-5c7c5a00-5c29-11eb-8af9-3f640e5d6827.png">
