### ISSUE TITLE
Time picker field

### ISSUE THREAD

**Issue by microerror** [LeanAdmin/feature-discussions#16]
Hello and thank you for your effort. I wanted to suggest adding a time picker field where user would be able to pick hours in days, 24 hour format for cultured people and 12 hour format for savages across the sea.

**Comment by stancl** [comment]
You can use React in your Livewire components 👍🏻

**Comment by microerror** [comment]
I don't understand... what does React have to do with LiveWire?

**Comment by stancl** [comment]
Sorry :/

**Comment by robertorinaldi-dev** [comment]
I think it is appropriate to block and report the user
