### ISSUE TITLE
Integration with Blueprint

### ISSUE THREAD

**Issue by stancl** [LeanAdmin/feature-discussions#18]
Basically https://github.com/Naoray/blueprint-nova-addon but ported for Lean syntax

**Comment by stancl** [comment]
We'll have a better solution for this

**Comment by cjcrawford** [comment]
I was just to the point in my fresh install where I was looking for generators or automation tools and noticed this roadmap issue as well as #4 (TallForms field mapping).

Taking a further look into BluePrint I see they have a community package for TallForm generators.

Curious what direction you were planning to take here, but I'd love to take a crack at an add on package that uses both of those packages as an artisan interactive approach.
