### ISSUE TITLE
Modals for editing child relations

### ISSUE THREAD

**Issue by stancl** [LeanAdmin/feature-discussions#2]
This will let you edit child resources when editing the parent. For example, if you're editing an Order, you will be able to edit its Products on the same page.

We'll show a slideover/modal on the right side of the screen. The modal will contain the Edit action for the child resource.

**Comment by molcsab** [comment]
Yes please

**Comment by stancl** [comment]
Limiting the scope of this for now. We'll use a single modal and later maybe support infinite nesting.

**Comment by stancl** [comment]
Fully implemented. Modals are not _nested_ as in overlaid on top of each other, but they can be infinitely nested they have back buttons.
