### ISSUE TITLE
PHP 8 only

### ISSUE THREAD

**Issue by stancl** [LeanAdmin/feature-discussions#3]
PHP 8 brings a lot of good new syntax. Usually, I would use fresh releases in my apps, but older releases in packages to support more applications.

However, due to the nature of this package (very new tech — Laravel 8, Livewire 2, Tailwind CSS 2), I think it wouldn't really prevent many people from using it, since they're already embracing cutting edge tech.

This will only take place when PHP 8 has decent ecosystem support. Right now some PHP extensions, packages, and IDE plugins still lack PHP 8 support, but this is improving rapidly. So in the next 1-2 months, we might go for PHP 8 only.

I'd appreciate any arguments, especially counter-arguments.

**Comment by viezel** [comment]
agree this makes sense. Most projects using Lean will be greenfield  - so why not push it to the newest. 👍

**Comment by stancl** [comment]
Yeah, that's the line of thought.

I think I'll wait like a month or two until the tooling is there and I'll make the switch.
